version: '3.9'
services:
  postgres:
    image: postgres:16.1
    container_name: postgres
    environment:
      POSTGRES_DB: transaction_manager_db
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"

  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
      target: release_image
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    depends_on:
      - postgres
    ports:
      - "8080:8080"

  tests:
    container_name: tests
    build:
      context: .
      dockerfile: Dockerfile
      target: unit_tests
    environment:
      - TESTCONTAINERS_HOST_OVERRIDE=host.docker.internal
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

networks:
  my-network: